import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryblokProvider from "@/components/storyblok-provider";
import Script from "next/script";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken: "rkUjJeE1nvv8JZ3LEeSJxAtt",
  use: [apiPlugin],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
        <Script src="/js-files/jquery.min.js" strategy="beforeInteractive" />
        <Script src="/js-files/vendors.js" strategy="beforeInteractive" />
        <Script src="/js-files/main.js" strategy="beforeInteractive" />
        <Script src="/js-files/magnific.min.js" strategy="beforeInteractive" />
      </html>
    </StoryblokProvider>
  );
}
